### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by KyleBrost** [kedarvj/mysqldumpsplitter#18]
I cloned the latest version (6.2) and attempted to use it and I get no errors and no output when it runs.  Then I used version 6.1 and it works as expected.  Used the following command:

sh mysqldumpsplitter.sh --source db.sql --extract DB --match_str zoom_dev3_menu

I think something is broken in the new version.

**Comment by ochan1** [comment]
Yeah, there's something broken
I went back to an earlier Master branch commit and it worked
Specifically this commit: https://github.com/kedarvj/mysqldumpsplitter/tree/1931aedc517d9105897c4a76220bda4de49fa270

used `git checkout 1931aedc517d9105897c4a76220bda4de49fa270`

**Comment by kedarvj** [comment]
The change of PV has been reverted.
