### ISSUE TITLE
multiple file processing? why?

### ISSUE THREAD

**Issue by cypa** [kedarvj/mysqldumpsplitter#22]
as I see the script process source file many times, is it correct? 
for ALLTABLES that would be number of tables + 1? 

look, I have 74Gb gzipped mysqldump file (350+ Gb ungzipped size)  with 615 tables in it ...

**Comment by kedarvj** [comment]
Hi @cypa,

Yes, unfortunatly current design is actually reading this multiple times. If you see the #TODo section I have and was working on optimizing the process of extraction but I couldn't finish it yet. Let me see to get a new branch started and post the "working" code of the improved approach and mostly it should get you what you want. 

Thanks,
Kedar

**Comment by cypa** [comment]
nice ... 
I've solved my problem yesterday, actually found this on stackoverflow 
```
gunzip -c db.mysqldump.gz | pv | awk 'BEGIN {output = "comments"; }
$data ~ /^-- Table structure for table/ {close(output); output = substr($6,2,length($6)-2); }
{if (output == "table_name") { print $data | "gzip -c > "output".gz";}}';
```
this extracts the table "table_name" only, to extract all the tables remove the if clause

**Comment by cypa** [comment]
moreover, today on telegram chat seasoned DBA told me there is plenty of tools nowadays 
- mysqlpump
- MySQL Shell 
- xtrabackup 
to do all these things, 
I personally think best solution is to adapt one of BigData formats like ORC and Parquet

**Comment by kedarvj** [comment]
Nice...  Mydumper is yet another backup tool but I am not sure what you're trying to achieve here. MySQL-Shell and Xtrabackup has nothing to do with the logical backups! You may have your reasons to choose the right database  solution or file formats but it is not MySQL and this script I wrote is specific to MySQL's logical backup. 

Anyhow, if you need my input, do share your issue. Ofcourse I will improve mysqldumpsplitter with priority.

Thanks

**Comment by cypa** [comment]
thank you for you support, 
my issue have been solved with awk script above
