### ISSUE TITLE
Using custom compression command (gzip --rsyncable)

### ISSUE THREAD

**Issue by berarma** [kedarvj/mysqldumpsplitter#5]
I'm evaluating using this script together with mysqldump to do consistent backups that are splitted to several files for convenience. It looks incredibly well, I only found one missing feature.

I want to use the ```--rsyncable``` command-line option in gzip and pigz. This option is useful when the files are going to be transfered or backed up with any solution based on rsync. It can reduce the amount of data to transfer/store on consecutive dumps.

Now I think it's not possible to use this option without modifying the script.

**Comment by bendathierrycom** [comment]
Maybe making a script of your own in order to do an rsync of the output folder to your remote destination path. Anyway I hope you have done this since 2 years ;)

**Comment by berarma** [comment]
I think you haven't understood the issue. Anyway, I have moved past it, I didn't even remember about this.
